/** FoodGuideDict 시드 — 연령x기질 조합 확대 (20개) + 레시피 */

export const FOOD_GUIDES = [
  // ===== 영아 (0~24개월) =====
  { targetAgeMin: 0, targetAgeMax: 24, suitableType: '활동형', foods: [
    { name: '고구마 퓨레', benefit: '에너지 보충과 소화가 쉬운 이유식', caution: '처음엔 소량부터',
      recipe: ['고구마를 깨끗이 씻어 찐다', '포크로 으깨어 부드럽게 만든다', '모유나 분유를 조금 넣어 농도를 맞춘다'],
      youtubeQuery: '아기 고구마 퓨레 이유식 만들기' },
    { name: '소고기 퓨레', benefit: '철분 보충으로 활발한 성장 지원', caution: '알레르기 확인',
      recipe: ['소고기를 핏물 빼고 삶는다', '잘게 다진 후 믹서기에 곱게 간다', '육수를 넣어 농도를 조절한다'],
      youtubeQuery: '아기 소고기 퓨레 이유식' },
    { name: '바나나', benefit: '칼륨 풍부, 에너지 보충',
      recipe: ['잘 익은 바나나를 포크로 으깬다', '모유나 분유와 섞어 부드럽게 만든다'],
      youtubeQuery: '아기 바나나 이유식 만들기' },
    { name: '닭가슴살 퓨레', benefit: '양질의 단백질 공급',
      recipe: ['닭가슴살을 깨끗이 씻어 삶는다', '잘게 찢은 후 믹서기에 곱게 간다', '육수를 넣어 부드럽게 만든다'],
      youtubeQuery: '아기 닭가슴살 퓨레 이유식' },
  ]},
  { targetAgeMin: 0, targetAgeMax: 24, suitableType: '감성형', foods: [
    { name: '아보카도', benefit: '두뇌 발달에 좋은 건강한 지방', caution: '알레르기 확인',
      recipe: ['잘 익은 아보카도를 반으로 자른다', '숟가락으로 과육을 떠서 으깬다', '모유와 섞어 부드럽게 만든다'],
      youtubeQuery: '아기 아보카도 이유식 만들기' },
    { name: '단호박 퓨레', benefit: '비타민A 풍부, 시각 발달',
      recipe: ['단호박을 씻어 찜기에 찐다', '껍질을 벗기고 포크로 으깬다', '물이나 분유로 농도를 맞춘다'],
      youtubeQuery: '아기 단호박 퓨레 이유식' },
    { name: '두부', benefit: '단백질 보충, 부드러운 식감', caution: '대두 알레르기 확인',
      recipe: ['연두부를 끓는 물에 살짝 데친다', '포크로 곱게 으깬다', '채소 퓨레와 섞어 줄 수 있다'],
      youtubeQuery: '아기 두부 이유식 만들기' },
    { name: '요거트', benefit: '장 건강과 면역력 강화', caution: '무가당 제품 선택',
      recipe: ['무가당 플레인 요거트를 준비한다', '과일 퓨레를 소량 섞어준다'],
      youtubeQuery: '아기 요거트 이유식 과일' },
  ]},
  { targetAgeMin: 0, targetAgeMax: 24, suitableType: '탐구형', foods: [
    { name: '브로콜리 퓨레', benefit: '비타민C와 섬유질로 면역력 강화',
      recipe: ['브로콜리를 작은 송이로 나눈다', '끓는 물에 3분 정도 데친다', '믹서기에 물과 함께 곱게 간다'],
      youtubeQuery: '아기 브로콜리 퓨레 이유식' },
    { name: '계란 노른자', benefit: '두뇌 발달에 필수인 콜린 함유', caution: '흰자는 돌 이후',
      recipe: ['달걀을 완숙으로 삶는다', '노른자만 분리하여 으깬다', '물이나 육수로 농도를 조절한다'],
      youtubeQuery: '아기 계란 노른자 이유식' },
    { name: '오트밀', benefit: '천천히 에너지를 공급해 집중력 유지',
      recipe: ['오트밀을 물에 넣고 약불에 끓인다', '부드러워질 때까지 저어준다', '과일 퓨레를 곁들인다'],
      youtubeQuery: '아기 오트밀 이유식 만들기' },
    { name: '당근 퓨레', benefit: '베타카로틴으로 시력 발달 지원',
      recipe: ['당근을 껍질 벗기고 잘게 썬다', '부드러워질 때까지 삶는다', '삶은 물과 함께 믹서기에 간다'],
      youtubeQuery: '아기 당근 퓨레 이유식' },
  ]},
  { targetAgeMin: 0, targetAgeMax: 24, suitableType: '조화형', foods: [
    { name: '감자 퓨레', benefit: '부드럽고 소화하기 쉬운 탄수화물',
      recipe: ['감자를 껍질 벗기고 삶는다', '포크로 곱게 으깬다', '분유를 넣어 부드럽게 만든다'],
      youtubeQuery: '아기 감자 퓨레 이유식' },
    { name: '배 퓨레', benefit: '수분 보충과 소화 도움',
      recipe: ['배를 껍질 벗기고 잘게 썬다', '약불에 살짝 익힌다', '믹서기에 곱게 간다'],
      youtubeQuery: '아기 배 퓨레 이유식' },
    { name: '쌀미음', benefit: '가장 안전한 첫 이유식',
      recipe: ['쌀을 30분 이상 불린다', '물을 넉넉히 넣고 죽을 끓인다', '체에 걸러 미음만 따른다'],
      youtubeQuery: '아기 쌀미음 첫 이유식 만들기' },
    { name: '애호박 퓨레', benefit: '비타민 풍부하고 알레르기 위험 낮음',
      recipe: ['애호박을 껍질 벗기고 잘게 썬다', '찜기에 부드럽게 찐다', '믹서기에 곱게 간다'],
      youtubeQuery: '아기 애호박 퓨레 이유식' },
  ]},
  { targetAgeMin: 0, targetAgeMax: 24, suitableType: '분석형', foods: [
    { name: '연두부', benefit: '두뇌 발달을 위한 양질의 식물성 단백질',
      recipe: ['연두부를 끓는 물에 살짝 데친다', '숟가락으로 곱게 으깬다'],
      youtubeQuery: '아기 연두부 이유식 만들기' },
    { name: '시금치 퓨레', benefit: '철분과 엽산으로 인지 발달 지원', caution: '질산염 주의, 소량부터',
      recipe: ['시금치를 깨끗이 씻어 데친다', '찬물에 헹궈 물기를 짠다', '믹서기에 물과 함께 곱게 간다'],
      youtubeQuery: '아기 시금치 퓨레 이유식' },
    { name: '참치 퓨레', benefit: 'DHA로 두뇌 신경 발달 촉진', caution: '수은 함량 확인',
      recipe: ['참치캔의 기름을 빼고 끓는 물에 데친다', '포크로 잘게 부순다', '채소 퓨레와 섞어준다'],
      youtubeQuery: '아기 참치 이유식 만들기' },
    { name: '완두콩 퓨레', benefit: '식물성 단백질과 비타민B군 풍부',
      recipe: ['완두콩을 부드럽게 삶는다', '믹서기에 물과 함께 곱게 간다', '체에 걸러 껍질을 제거한다'],
      youtubeQuery: '아기 완두콩 퓨레 이유식' },
  ]},

  // ===== 유아 (25~72개월) =====
  { targetAgeMin: 25, targetAgeMax: 72, suitableType: '활동형', foods: [
    { name: '닭가슴살 구이', benefit: '근육 발달을 위한 양질의 단백질',
      recipe: ['닭가슴살에 소금을 살짝 뿌린다', '팬에 올리브유를 두르고 앞뒤로 굽는다', '한입 크기로 잘라 준다'],
      youtubeQuery: '아이 닭가슴살 구이 유아식' },
    { name: '현미밥', benefit: '지속적인 에너지 공급',
      recipe: ['현미를 2시간 이상 불린다', '백미와 7:3 비율로 섞는다', '밥솥에 물을 약간 더 넣고 짓는다'],
      youtubeQuery: '아이 현미밥 맛있게 짓기' },
    { name: '고구마 스틱', benefit: '건강한 간식, 식이섬유 풍부',
      recipe: ['고구마를 스틱 모양으로 자른다', '올리브유를 살짝 발라 오븐에 굽는다', '180도에서 20분 구운다'],
      youtubeQuery: '아이 고구마 스틱 간식 만들기' },
    { name: '우유', benefit: '칼슘으로 뼈 성장 지원', caution: '유당불내증 확인',
      recipe: ['미지근하게 데워서 준다', '바나나와 함께 스무디로 만들 수 있다'],
      youtubeQuery: '아이 우유 바나나 스무디' },
  ]},
  { targetAgeMin: 25, targetAgeMax: 72, suitableType: '감성형', foods: [
    { name: '블루베리', benefit: '안토시아닌으로 감성 발달과 면역력 강화',
      recipe: ['블루베리를 깨끗이 씻는다', '요거트 위에 올려준다', '꿀을 살짝 뿌려도 좋다'],
      youtubeQuery: '아이 블루베리 요거트 간식' },
    { name: '치즈', benefit: '칼슘과 단백질로 안정감 있는 성장',
      recipe: ['모짜렐라 치즈를 한입 크기로 자른다', '방울토마토와 함께 꼬치에 꽂는다'],
      youtubeQuery: '아이 치즈 간식 만들기' },
    { name: '고구마 라떼(무가당)', benefit: '트립토판 함유로 정서 안정 도움',
      recipe: ['고구마를 쪄서 으깬다', '따뜻한 우유를 넣고 섞는다', '믹서기에 곱게 갈아준다'],
      youtubeQuery: '고구마 라떼 무가당 만들기' },
    { name: '바나나 팬케이크', benefit: '세로토닌 전구체로 기분 조절 도움',
      recipe: ['바나나를 으깨고 달걀과 섞는다', '밀가루를 조금 넣어 반죽한다', '팬에 작게 동그랗게 부친다'],
      youtubeQuery: '아이 바나나 팬케이크 만들기' },
  ]},
  { targetAgeMin: 25, targetAgeMax: 72, suitableType: '탐구형', foods: [
    { name: '연어 볶음밥', benefit: 'DHA로 집중력과 호기심 지원',
      recipe: ['연어를 구워서 잘게 부순다', '밥과 채소를 함께 볶는다', '연어를 넣고 간장으로 간한다'],
      youtubeQuery: '아이 연어 볶음밥 만들기' },
    { name: '아몬드', benefit: '비타민E로 두뇌 세포 보호', caution: '견과 알레르기 주의, 잘게 부숴서',
      recipe: ['아몬드를 잘게 다진다', '요거트나 시리얼 위에 뿌려준다'],
      youtubeQuery: '아이 견과류 간식 만들기' },
    { name: '달걀 프라이', benefit: '콜린으로 기억력 향상',
      recipe: ['팬에 버터를 살짝 녹인다', '달걀을 깨넣고 약불에 익힌다', '반숙이나 완숙으로 취향에 맞게 익힌다'],
      youtubeQuery: '아이 달걀 프라이 부드럽게' },
    { name: '김', benefit: '요오드로 갑상선 기능 지원',
      recipe: ['김에 참기름을 살짝 바른다', '소금을 미세하게 뿌린다', '밥과 함께 먹거나 김밥을 만든다'],
      youtubeQuery: '아이 김 간식 만들기' },
  ]},
  { targetAgeMin: 25, targetAgeMax: 72, suitableType: '조화형', foods: [
    { name: '잡곡밥', benefit: '균형 잡힌 영양소 공급',
      recipe: ['잡곡을 2시간 이상 불린다', '백미와 잡곡을 8:2로 섞는다', '물을 약간 더 넣고 밥을 짓는다'],
      youtubeQuery: '아이 잡곡밥 맛있게 짓기' },
    { name: '된장국', benefit: '발효식품으로 장 건강 지원',
      recipe: ['멸치 육수를 낸다', '두부와 애호박을 넣는다', '된장을 풀어 끓인다'],
      youtubeQuery: '아이 된장국 맛있게 끓이기' },
    { name: '사과', benefit: '비타민과 식이섬유의 균형',
      recipe: ['사과를 깨끗이 씻어 껍질을 벗긴다', '먹기 좋은 크기로 자른다', '레몬즙을 살짝 뿌려 갈변을 방지한다'],
      youtubeQuery: '아이 사과 간식 예쁘게 자르기' },
    { name: '두부 스테이크', benefit: '식물성 단백질로 성장 지원',
      recipe: ['두부를 도톰하게 썰어 물기를 뺀다', '팬에 올리브유를 두르고 노릇하게 굽는다', '간장 소스를 곁들인다'],
      youtubeQuery: '아이 두부 스테이크 만들기' },
  ]},
  { targetAgeMin: 25, targetAgeMax: 72, suitableType: '분석형', foods: [
    { name: '호두', benefit: '오메가3로 논리적 사고 지원', caution: '견과 알레르기 주의',
      recipe: ['호두를 잘게 다진다', '꿀과 섞어 에너지볼을 만든다'],
      youtubeQuery: '아이 호두 간식 에너지볼' },
    { name: '고등어 구이', benefit: 'DHA 풍부, 집중력 향상', caution: '뼈 주의',
      recipe: ['고등어에 소금을 살짝 뿌린다', '에어프라이어 180도에서 15분 굽는다', '뼈를 제거하고 살만 발라준다'],
      youtubeQuery: '아이 고등어 구이 뼈 발라주기' },
    { name: '시금치 나물', benefit: '철분으로 두뇌 산소 공급',
      recipe: ['시금치를 데쳐서 찬물에 헹군다', '참기름과 소금으로 무친다', '깨를 솔솔 뿌린다'],
      youtubeQuery: '아이 시금치 나물 맛있게' },
    { name: '현미 크래커', benefit: '비타민B군으로 신경 발달 지원',
      recipe: ['현미가루와 물을 반죽한다', '얇게 밀어 모양을 낸다', '오븐에 바삭하게 굽는다'],
      youtubeQuery: '아이 현미 크래커 만들기' },
  ]},

  // ===== 초등 (73개월+) =====
  { targetAgeMin: 73, targetAgeMax: 200, suitableType: '활동형', foods: [
    { name: '닭가슴살 샐러드', benefit: '근육 회복과 체력 유지',
      recipe: ['닭가슴살을 삶아서 잘게 찢는다', '채소를 씻어 한입 크기로 자른다', '올리브유 드레싱을 뿌려 버무린다'],
      youtubeQuery: '아이 닭가슴살 샐러드 만들기' },
    { name: '바나나 스무디', benefit: '운동 전후 에너지 보충',
      recipe: ['바나나와 우유를 믹서기에 넣는다', '꿀을 한 스푼 넣고 갈아준다', '얼음을 넣으면 더 시원하게 즐길 수 있다'],
      youtubeQuery: '아이 바나나 스무디 만들기' },
    { name: '잡곡밥', benefit: '지속적인 에너지와 식이섬유',
      recipe: ['잡곡을 2시간 이상 불린다', '백미와 잡곡을 7:3으로 섞는다', '물을 약간 더 넣고 밥을 짓는다'],
      youtubeQuery: '잡곡밥 맛있게 짓는 법' },
    { name: '고구마', benefit: '복합 탄수화물로 꾸준한 에너지',
      recipe: ['고구마를 깨끗이 씻는다', '에어프라이어 200도에서 30분 굽는다', '반으로 잘라 버터를 올린다'],
      youtubeQuery: '에어프라이어 군고구마 만들기' },
    { name: '두유', benefit: '식물성 단백질 보충', caution: '대두 알레르기 확인',
      recipe: ['콩을 하룻밤 불린다', '삶은 콩과 물을 믹서기에 간다', '체에 걸러 따뜻하게 데운다'],
      youtubeQuery: '집에서 두유 만들기' },
  ]},
  { targetAgeMin: 73, targetAgeMax: 200, suitableType: '감성형', foods: [
    { name: '다크 초콜릿', benefit: '세로토닌 분비 촉진으로 기분 개선', caution: '카카오 70% 이상, 소량만',
      recipe: ['다크 초콜릿을 중탕으로 녹인다', '과일이나 견과류에 묻혀 굳힌다'],
      youtubeQuery: '아이 초콜릿 과일 간식 만들기' },
    { name: '연어 초밥', benefit: 'DHA와 오메가3로 정서 안정',
      recipe: ['초밥용 밥을 짓고 식초를 섞는다', '연어회를 올린다', '손으로 쥐어 모양을 잡는다'],
      youtubeQuery: '아이 연어 초밥 집에서 만들기' },
    { name: '아보카도 토스트', benefit: '건강한 지방으로 뇌 기능 지원',
      recipe: ['식빵을 토스터에 굽는다', '아보카도를 으깨어 빵 위에 바른다', '소금과 레몬즙을 살짝 뿌린다'],
      youtubeQuery: '아이 아보카도 토스트 만들기' },
    { name: '캐모마일 차', benefit: '긴장 완화와 수면 도움', caution: '카페인 없음 확인',
      recipe: ['캐모마일 티백을 컵에 넣는다', '뜨거운 물을 부어 3분간 우린다', '미지근하게 식혀서 마신다'],
      youtubeQuery: '아이 캐모마일 차 만들기' },
    { name: '견과류 믹스', benefit: '마그네슘으로 스트레스 완화', caution: '알레르기 확인',
      recipe: ['아몬드, 호두, 캐슈넛을 준비한다', '팬에 살짝 볶아 고소하게 한다', '말린 과일과 섞어 보관한다'],
      youtubeQuery: '아이 견과류 믹스 간식 만들기' },
  ]},
  { targetAgeMin: 73, targetAgeMax: 200, suitableType: '탐구형', foods: [
    { name: '연어', benefit: '오메가3로 집중력과 두뇌 발달 지원',
      recipe: ['연어에 소금, 후추를 뿌린다', '팬에 올리브유를 두르고 앞뒤로 굽는다', '레몬즙을 뿌려 마무리한다'],
      youtubeQuery: '아이 연어 스테이크 만들기' },
    { name: '블루베리', benefit: '항산화 성분으로 기억력 향상',
      recipe: ['블루베리를 깨끗이 씻는다', '요거트 볼에 블루베리와 그래놀라를 담는다', '꿀을 살짝 뿌린다'],
      youtubeQuery: '아이 블루베리 요거트볼 만들기' },
    { name: '호두', benefit: '두뇌 영양 간식, 불포화지방산', caution: '견과류 알레르기 주의',
      recipe: ['호두를 팬에 살짝 볶는다', '꿀과 시나몬을 넣어 코팅한다', '식혀서 간식으로 먹는다'],
      youtubeQuery: '꿀 호두 간식 만들기' },
    { name: '달걀', benefit: '콜린으로 학습 능력 강화',
      recipe: ['물에 달걀을 넣고 삶는다', '끓은 후 10분이면 완숙이 된다', '소금이나 간장에 찍어 먹는다'],
      youtubeQuery: '맛있는 삶은 달걀 만들기' },
    { name: '카카오 닙스', benefit: '플라보노이드로 인지 기능 향상', caution: '카페인 소량 함유',
      recipe: ['카카오 닙스를 요거트에 뿌린다', '바나나와 함께 스무디로 만들어도 좋다'],
      youtubeQuery: '카카오닙스 요거트 간식' },
  ]},
  { targetAgeMin: 73, targetAgeMax: 200, suitableType: '분석형', foods: [
    { name: '계란', benefit: '콜린 성분으로 집중력 강화',
      recipe: ['달걀을 풀어 소금간을 한다', '팬에 버터를 녹이고 스크램블을 만든다', '치즈를 올려 마무리한다'],
      youtubeQuery: '부드러운 스크램블 에그 만들기' },
    { name: '시금치', benefit: '철분으로 두뇌 산소 공급 도움',
      recipe: ['시금치를 데쳐서 찬물에 헹군다', '참기름과 다진 마늘로 무친다', '깨를 뿌려 마무리한다'],
      youtubeQuery: '시금치 나물 맛있게 무치기' },
    { name: '고등어', benefit: 'DHA 풍부, 논리적 사고력 지원', caution: '뼈 주의',
      recipe: ['고등어에 소금을 뿌려 10분 둔다', '팬이나 그릴에 노릇하게 굽는다', '무조림과 함께 먹으면 좋다'],
      youtubeQuery: '고등어 구이 맛있게 굽는 법' },
    { name: '렌틸콩 수프', benefit: '철분과 엽산으로 인지 발달',
      recipe: ['렌틸콩을 씻어 물에 담근다', '양파, 당근과 함께 끓인다', '소금으로 간을 맞추고 믹서기로 갈아준다'],
      youtubeQuery: '렌틸콩 수프 만들기' },
    { name: '그릭 요거트', benefit: '단백질과 프로바이오틱스',
      recipe: ['그릭 요거트를 그릇에 담는다', '꿀과 견과류를 토핑한다', '계절 과일을 곁들인다'],
      youtubeQuery: '그릭요거트 과일 볼 만들기' },
  ]},
  { targetAgeMin: 73, targetAgeMax: 200, suitableType: '조화형', foods: [
    { name: '현미 비빔밥', benefit: '다양한 영양소의 균형 있는 식사',
      recipe: ['현미밥을 짓고 나물을 준비한다', '고추장과 참기름을 넣는다', '골고루 비벼 먹는다'],
      youtubeQuery: '아이 현미 비빔밥 만들기' },
    { name: '미역국', benefit: '미네랄과 식이섬유로 균형 성장',
      recipe: ['미역을 물에 불려 먹기 좋게 자른다', '참기름에 미역을 볶는다', '물을 넣고 끓여 간장으로 간한다'],
      youtubeQuery: '맛있는 미역국 끓이기' },
    { name: '두부 샐러드', benefit: '식물성 단백질과 비타민 동시 섭취',
      recipe: ['두부를 깍둑썰기하여 팬에 굽는다', '채소를 씻어 한입 크기로 자른다', '두부와 채소를 섞고 드레싱을 뿌린다'],
      youtubeQuery: '두부 샐러드 만들기' },
    { name: '오렌지', benefit: '비타민C로 면역력 강화',
      recipe: ['오렌지를 깨끗이 씻는다', '껍질을 벗기고 먹기 좋게 자른다', '주스로 만들어도 좋다'],
      youtubeQuery: '오렌지 주스 만들기' },
    { name: '통밀빵 샌드위치', benefit: '균형 잡힌 한끼 식사',
      recipe: ['통밀빵에 크림치즈를 바른다', '상추, 토마토, 달걀을 넣는다', '빵을 덮고 반으로 자른다'],
      youtubeQuery: '아이 샌드위치 도시락 만들기' },
  ]},
];
