/** QuestionBank 시드 — 영아/유아/초등 각 20개 = 60개 */

export const QUESTIONS = [
  // ===== 영아 (0~24개월) 20개 =====
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '활동형', questionText: '아이의 수면 패턴은 어떤가요?', options: ['정해진 시간에 잘 자요', '불규칙하지만 잘 자요', '자주 깨고 보채요', '낮잠을 거의 안 자요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '감성형', questionText: '새로운 소리나 촉감에 어떻게 반응하나요?', options: ['호기심을 보이며 탐색해요', '놀라며 울어요', '무관심해요', '반복적으로 만지거나 들어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '탐구형', questionText: '낯선 물건을 보면 어떻게 하나요?', options: ['바로 손을 뻗어 잡으려 해요', '멀리서 관찰해요', '부모 얼굴을 보며 확인해요', '관심이 없어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '조화형', questionText: '다른 아기를 만나면 어떤 반응인가요?', options: ['미소를 지어요', '울거나 피해요', '가까이 다가가요', '무반응이에요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '분석형', questionText: '장난감을 줄 때 어떻게 놀아요?', options: ['뒤집고 분해하려 해요', '입에 넣어요', '흔들거나 두드려요', '한참 바라봐요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '활동형', questionText: '배밀이/기기 단계에서 아이의 활동량은?', options: ['쉴 새 없이 움직여요', '천천히 탐색해요', '한곳에 오래 있어요', '안아달라고 해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '감성형', questionText: '부모가 안 보이면 어떻게 반응하나요?', options: ['금방 울어요', '찾아다녀요', '혼자 놀아요', '상황에 따라 달라요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '탐구형', questionText: '이유식을 처음 접할 때 반응은?', options: ['호기심을 보이며 먹어봐요', '거부하고 뱉어요', '천천히 적응해요', '손으로 만지며 탐색해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '조화형', questionText: '목욕 시간에 아이의 반응은?', options: ['물을 좋아하며 놀아요', '울며 싫어해요', '차분하게 있어요', '물장구치며 신나해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '분석형', questionText: '그림책을 보여주면 어떻게 하나요?', options: ['손으로 그림을 짚어요', '페이지를 빨리 넘겨요', '한 페이지를 오래 봐요', '책을 입에 넣어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '활동형', questionText: '음악이 나오면 어떻게 반응하나요?', options: ['몸을 흔들어요', '가만히 들어요', '소리 나는 쪽을 봐요', '무관심해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '감성형', questionText: '잠들기 전 아이의 습관은?', options: ['인형이나 담요를 꼭 잡아요', '엄마 품에서만 자요', '스스로 뒤척이다 자요', '자장가를 들어야 해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '탐구형', questionText: '새로운 장소에 가면 어떤가요?', options: ['바로 돌아다니며 탐색해요', '부모에게 달라붙어요', '주위를 관찰한 뒤 움직여요', '울거나 불안해해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '조화형', questionText: '형제자매나 또래와 있을 때 반응은?', options: ['함께 놀려고 해요', '따로 놀아요', '관찰만 해요', '장난감을 빼앗으려 해요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '분석형', questionText: '쌓기 놀이를 할 때 어떻게 하나요?', options: ['차곡차곡 쌓아요', '바로 무너뜨려요', '부모가 쌓는 걸 봐요', '관심이 없어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '활동형', questionText: '아이의 전반적인 기분 상태는?', options: ['대체로 활발하고 기분이 좋아요', '예민하고 자주 울어요', '차분하고 조용해요', '기분 변화가 빨라요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '감성형', questionText: '아이가 칭찬받을 때 반응은?', options: ['활짝 웃어요', '부끄러워해요', '반복하려 해요', '별 반응이 없어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '탐구형', questionText: '바깥 산책 시 아이가 집중하는 것은?', options: ['움직이는 것 (차, 동물)', '꽃이나 나뭇잎', '다른 사람들', '특별히 없어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '조화형', questionText: '아이가 불편할 때 표현 방식은?', options: ['크게 울어요', '칭얼거려요', '표정으로 보여줘요', '몸을 비틀어요'] },
  { targetAgeMin: 0, targetAgeMax: 24, sajuType: '분석형', questionText: '까꿍 놀이를 할 때 반응은?', options: ['깔깔 웃어요', '진지하게 쳐다봐요', '따라 하려 해요', '금방 싫증내요'] },

  // ===== 유아 (25~72개월) 20개 =====
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '조화형', questionText: '또래 친구와 놀 때 어떤 모습인가요?', options: ['리더 역할을 해요', '잘 어울리며 양보해요', '혼자 놀기를 선호해요', '관찰하다가 합류해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '활동형', questionText: '감정 표현 방식은 어떤가요?', options: ['크게 웃고 크게 울어요', '조용히 표현해요', '말로 잘 설명해요', '몸으로 표현해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '탐구형', questionText: '"왜?"라는 질문을 얼마나 자주 하나요?', options: ['끊임없이 질문해요', '가끔 궁금해해요', '거의 안 물어봐요', '직접 알아보려 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '분석형', questionText: '퍼즐이나 블록 놀이를 좋아하나요?', options: ['매우 좋아해요', '가끔 해요', '선호하지 않아요', '끝까지 완성해야 직성이 풀려요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '감성형', questionText: '슬픈 장면(동화, 영상)을 보면 어떤가요?', options: ['함께 울어요', '왜 슬픈지 물어봐요', '별 반응 없어요', '안아달라고 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '활동형', questionText: '놀이터에서 주로 어떤 놀이를 하나요?', options: ['미끄럼틀, 그네 등 활동적인 놀이', '모래놀이처럼 조용한 놀이', '친구와 역할놀이', '혼자 산책하듯 돌아다녀요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '조화형', questionText: '친구와 갈등이 생기면 어떻게 하나요?', options: ['양보해요', '울면서 속상해해요', '자기 주장을 강하게 해요', '부모에게 도움을 요청해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '탐구형', questionText: '새로운 장난감을 받으면 어떻게 하나요?', options: ['어떻게 작동하는지 뜯어봐요', '설명서를 봐달라고 해요', '신나서 바로 놀아요', '기존 장난감을 더 좋아해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '분석형', questionText: '규칙이 있는 게임을 할 때 반응은?', options: ['규칙을 잘 따라요', '규칙을 바꾸려 해요', '규칙을 이해하기 어려워해요', '이기려고 열심히 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '감성형', questionText: '좋아하는 동화 캐릭터가 있나요?', options: ['공주/왕자 같은 캐릭터', '동물 캐릭터', '영웅 캐릭터', '특별히 좋아하는 캐릭터가 없어요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '활동형', questionText: '식사 시간에 아이의 모습은?', options: ['빨리 먹고 놀러 가요', '골고루 잘 먹어요', '편식이 심해요', '먹으면서 이야기해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '조화형', questionText: '동생이나 어린 아이를 대할 때 어떤가요?', options: ['잘 돌봐주려 해요', '질투해요', '무관심해요', '장난치며 놀아줘요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '탐구형', questionText: '자연(벌레, 꽃, 돌멩이)에 대한 관심은?', options: ['매우 관심이 많아요', '보통이에요', '무서워하거나 싫어해요', '수집하려 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '분석형', questionText: '숫자나 글자에 관심을 보이나요?', options: ['이미 몇 개 읽어요', '관심을 보이기 시작해요', '아직 관심 없어요', '패턴을 찾으려 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '감성형', questionText: '미술(그리기, 만들기) 활동을 좋아하나요?', options: ['매우 좋아해요', '가끔 해요', '다른 놀이를 더 좋아해요', '색칠만 좋아해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '활동형', questionText: '비 오는 날 실내에서 어떻게 지내나요?', options: ['답답해하며 돌아다녀요', '그림 그리거나 책을 봐요', '영상을 보고 싶어해요', '역할놀이를 해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '조화형', questionText: '잘못했을 때 아이의 반응은?', options: ['바로 미안하다고 해요', '변명을 해요', '울어요', '모르는 척해요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '탐구형', questionText: '좋아하는 놀이 유형은?', options: ['실험/만들기 놀이', '역할놀이 (소꿉, 마트)', '운동/신체 놀이', '조용한 놀이 (퍼즐, 색칠)'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '분석형', questionText: '이야기를 들을 때 어떤 모습인가요?', options: ['끝까지 집중해서 들어요', '질문을 많이 해요', '중간에 딴짓을 해요', '같이 이야기를 만들어요'] },
  { targetAgeMin: 25, targetAgeMax: 72, sajuType: '감성형', questionText: '잠자리에서 하는 행동은?', options: ['이야기를 해달라고 해요', '인형을 안고 자요', '혼자 잘 자요', '부모 옆에서만 자요'] },

  // ===== 초등 (73개월~) 20개 =====
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '탐구형', questionText: '새로운 것을 배울 때 어떤 방식을 선호하나요?', options: ['직접 해보면서 배워요', '설명을 듣고 이해해요', '책이나 영상으로 먼저 봐요', '친구와 함께 배워요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '분석형', questionText: '스트레스를 받으면 어떤 반응을 보이나요?', options: ['혼자 조용히 있고 싶어해요', '짜증을 내거나 화를 내요', '부모에게 이야기해요', '다른 활동으로 전환해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '활동형', questionText: '방과 후에 주로 무엇을 하나요?', options: ['바깥에서 친구와 놀아요', '집에서 게임이나 영상을 봐요', '학원이나 학습을 해요', '취미 활동을 해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '조화형', questionText: '학교에서 친구 관계는 어떤가요?', options: ['친구가 많고 인기 있어요', '소수의 친한 친구가 있어요', '혼자 있는 걸 좋아해요', '갈등이 종종 있어요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '감성형', questionText: '좋아하는 과목은 무엇인가요?', options: ['국어/사회 (이야기, 토론)', '수학/과학 (문제 풀기)', '체육/음악/미술', '특별히 좋아하는 과목이 없어요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '탐구형', questionText: '궁금한 것이 생기면 어떻게 하나요?', options: ['인터넷/책에서 직접 찾아봐요', '부모나 선생님에게 물어봐요', '그냥 넘어가요', '친구와 의논해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '분석형', questionText: '숙제를 할 때 어떤 스타일인가요?', options: ['계획을 세워서 해요', '마지막에 몰아서 해요', '좋아하는 과목만 먼저 해요', '부모가 도와줘야 해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '활동형', questionText: '주말에 하고 싶은 것은?', options: ['바깥 활동 (운동, 놀이공원)', '집에서 쉬기 (게임, 독서)', '친구 만나기', '가족과 함께하기'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '조화형', questionText: '모둠 활동을 할 때 어떤 역할인가요?', options: ['리더/발표자', '아이디어를 내는 편', '시키는 걸 잘 해요', '정리/기록을 맡아요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '감성형', questionText: '감동적인 이야기를 읽으면?', options: ['눈물이 나요', '깊이 생각해요', '빨리 다음 이야기가 궁금해요', '별 감흥 없어요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '탐구형', questionText: '새로운 취미를 시작할 때?', options: ['열정적으로 빠져들어요', '시작은 하지만 금방 싫증내요', '신중하게 고민하고 시작해요', '친구가 하면 따라 해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '분석형', questionText: '시험이나 발표 전에 어떤가요?', options: ['미리 준비하고 연습해요', '긴장하지만 잘 해내요', '매우 긴장해요', '대충 준비해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '활동형', questionText: '좋아하는 운동이나 신체 활동은?', options: ['팀 스포츠 (축구, 농구)', '개인 운동 (수영, 달리기)', '댄스나 체조', '운동을 별로 안 좋아해요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '조화형', questionText: '친구가 힘들어할 때 어떻게 하나요?', options: ['위로해주고 들어줘요', '해결 방법을 제안해요', '같이 힘들어해요', '잘 모르겠어요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '감성형', questionText: '혼자만의 시간에 주로 무엇을 하나요?', options: ['그림 그리기/글쓰기', '음악 듣기', '공상/상상하기', '게임/영상 보기'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '탐구형', questionText: '장래 희망에 대해 이야기하나요?', options: ['구체적인 꿈이 있어요', '자주 바뀌어요', '아직 잘 모르겠대요', '여러 가지에 관심이 많아요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '분석형', questionText: '용돈을 받으면 어떻게 하나요?', options: ['모아두는 편이에요', '바로 써버려요', '계획적으로 써요', '필요한 것만 사요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '활동형', questionText: '아침에 일어나는 모습은?', options: ['스스로 잘 일어나요', '깨워야 해요', '기분에 따라 달라요', '일찍 일어나서 놀아요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '조화형', questionText: '규칙을 어겼을 때 반응은?', options: ['솔직하게 인정해요', '변명하거나 거짓말해요', '울거나 속상해해요', '왜 그런 규칙인지 따져요'] },
  { targetAgeMin: 73, targetAgeMax: 200, sajuType: '감성형', questionText: '가장 소중하게 여기는 것은?', options: ['가족', '친구', '반려동물/인형', '자기만의 물건/공간'] },
];
